[package]
name = "lish"
version = "0.0.0"
edition = "2021"

[dependencies]
liso = {path = "../.."}
shellish_parse = "2.0"

[target.'cfg(unix)'.dependencies]
nix = {version = "0.25", default-features = false, features=["signal"]}

[features]
default = []
no-unix = []